version: '3.7'
services:
    api:
        build: .
        depends_on:
            mongodb:
                condition: service_started
            mysql:
                condition: service_healthy
        ports:
            - "3000:3000"
        environment:
            WEBSERVER_PORT: 3000
            MYSQL_DATABASE_URL: mysql://chathappens:chathappens@mysql:3306/chathappens
            MONGODB_DATABASE_URL: mongodb://mongodb:27017/chat-happens
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: admin
            JWT_SECRET: mc5^$fedR8w<&pEEr4/Wp6m]K64u7M}J
            JWT_TTL_DAYS: 1
    mysql:
        image: "mysql:8.0"
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: 'chathappens'
            MYSQL_USER: 'chathappens'
            MYSQL_PASSWORD: 'chathappens'
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - mysql-data:/var/lib/mysql
    mongodb:
        image: mongo:7.0.0-rc4
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - "27017:27017"
        command: mongod
        volumes:
            - mongodb-data:/var/lib/mongodb
volumes:
    mysql-data:
    mongodb-data:
