version: '3'
services:
    api:
        build: .
        depends_on:
            - mongodb
        ports:
            - "3000:3000"
        environment:
            WEBSERVER_PORT: 3000
            MONGODB_HOST: mongodb
            MONGODB_PORT: 27017
            MONGODB_SCHEMA: chat-happens
            MONGODB_USERNAME: admin
            MONGODB_PASSWORD: admin

    #        command: prisma:dev:deploy
#    mysql:
#        image: "mysql"
#        environment:
#            MYSQL_DATABASE: 'chat-happens'
#            MYSQL_USER: 'user'
#            MYSQL_ROOT_PASSWORD: root
#        volumes:
#            - db-data:/foo
    mongodb:
        image: mongo:7.0.0-rc4
        environment:
            # provide your credentials here
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - "27017:27017"
        volumes:
            # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
            - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
        # no --auth is needed here as presence of username and password add this option automatically
        command: mongod
#volumes:
#    db-data:
#    message-data:
